Metro style applied
luan122/Gerador-de-CNPJ-e-CPF pull request #1
Opened 2019-10-11 16:33 UTC by viniciuskr

Visual improves

2019-10-11 17:03 UTC, luan122 requested changes
Muito bacana que alguém viu o projeto, deu fork e ainda o melhorou, criei ele quando eu estava no inicio da minha carreira como programador, nem lembrava mais dele! Obrigado! Assim que aceitar a PR irei modificiar o sobre :)

2019-10-11 17:03 UTC, luan122 commented on Gerador de CNPJ/MainWindow.cs
> +                    rtbResultado.Text = generator.CnpjSemMascara(Convert.ToInt32(txQuantidade.Text));
Removendo a thread pode acarretar em travamento da aplicação para quantidades grandes de numeros e ela não volta

2019-10-15 16:50 UTC, viniciuskr commented on Gerador de CNPJ/MainWindow.cs
> +                    rtbResultado.Text = generator.CnpjSemMascara(Convert.ToInt32(txQuantidade.Text));
perfeito, vou adaptar para manter a thread e apresentar um indicador de progresso

2019-10-17 14:18 UTC, luan122 reviewed
boa

2019-10-17 14:19 UTC, luan122 approved these changes

2019-10-17 14:19 UTC, merged